language: python
python:
  - 2.7
  - pypy
  - 3.5
  - 3.4
  - 3.3
  - 3.2
before_install:
  - pip install metakernel
  - pip install mathics
  - pip install jupyter_kernel_test
  - pip install unittest2
install:
  - python setup.py install
script:
  - python test.py
notifications:
email: false
