language: python
python:
  - 2.7
  - 3.5
  - 3.4
  - 3.3
before_install:
  - pip install git+https://github.com/mmatera/mathics
  - pip install ipywidgets
  - pip install ipykernel
  - pip install metakernel
  - pip install jupyter_kernel_test
  - pip install unittest2
install:
  - python setup.py install --mma-exec /home/travis/virtualenv/python2.7.9/bin/mathics
script:
  - python test.py
notifications:
email: false
